# Default configuration for MasterSMP Core plugin
default_color: "&#37BFF9"

FindPlayerWorlds:
  - "spawn:&#37BFF9:ꜱᴘᴀᴡɴ"
  - "afk:&#A303F9:ᴀꜰᴋ"
  - "world:&#37BFF9:ᴏᴠᴇʀᴡᴏʀʟᴅ"
  - "world_nether:&#37BFF9:ɴᴇᴛʜᴇʀ"
  - "world_the_end:&#37BFF9:ᴇɴᴅ"

messages:
  player_not_found: "&cThis user is offline or does not exist."
  never_played: "&cThis user has never played before."

ping:
  enabled: true
  self_message: "&#A8A8A8Your ping is &#37BEF8%ping%ms"
  target_message: "&#A8A8A8%player%'s ping is &#37BEF8%ping%ms"
  error_message: "&cThis user is offline or does not exist."
  error_sound: "ENTITY_VILLAGER_NO"

first_join:
  enabled: true
  join_message: "&#37bff9%player% &#C7CEDCjoined the server for the first time."
  messages:
    - "&#37bff9ᴡᴇʟᴄᴏᴍᴇ ᴛᴏ ᴍᴀꜱᴛᴇʀꜱᴍᴘ!"
    - "&#37bff9ᴊᴏɪɴ ᴛʜᴇ ᴍᴀꜱᴛᴇʀꜱᴍᴘ ᴅɪꜱᴄᴏʀᴅ ᴄᴏᴍᴍᴜɴɪᴛʏ!"
    - "&#37bff9● <open url:http://discord.gg/GXRFA8fx59>&#37bff9&ndsc.gg/mastersmc</open>"
  items:
    - "STONE_SWORD:1"
    - "COOKED_BEEF:16"
    - "CHAINMAIL_HELMET:1"
    - "CHAINMAIL_CHESTPLATE:1"
    - "CHAINMAIL_LEGGINGS:1"
    - "CHAINMAIL_BOOTS:1"

join_message: "&#37bff9%player% &#C7CEDCjoined the server."
quit_message: "&#37bff9%player% &#C7CEDCleft the server."

Fly:
  permission: mastersmp.fly.use
  FlyWorlds:
    - spawn
    - afk
  restricted_message: "&cYou are not allowed to do that in this region."

subscription:
  online_message: "&#a8a8a8You received &#00a4fc%rank% &#a8a8a8Rank!\n\n&#a8a8a8You have &#00a4fc%time% &#a8a8a8left of subscription time."
  offline_message: "&#a8a8a8You received &#00a4fc%rank% &#a8a8a8Rank!\n\n&#a8a8a8You have &#00a4fc%time% &#a8a8a8left of subscription time."
  expired_message: "&#a8a8a8Your &#00a4fc%rank% &#a8a8a8subscription has expired!"
  thank_you_message: "&#a8a8a8Thank you for being a part of &#00a4fcMasterSMP!"
  revoked_message: "&#a8a8a8Your &#00a4fc%rank% &#a8a8a8subscription has been revoked by an admin!"
